import { useEffect,useMemo,useRef,useState } from "react";

type Status="DRAFT"|"COMPLETED"|"ARCHIVED";
type Form=Record<string,string>;
type Item={id:number;sample_date:string;sample_name:string;calorimeter:string;status:Status;updated_at:string;wr_percent:string;wa_percent:string;aa_percent:string;sa_percent:string;va_percent:string;calculated:Record<string,string>};
const EMPTY:Form={sample_date:"",sample_name:"",calorimeter:"C200",sa_percent:"",alpha:"0.0015",wa_percent:"",aa_percent:"",wr_percent:"",hydrogen_input_percent:"",qb_a_1_kcal_kg:"",qb_a_2_kcal_kg:"",va_percent:"",lab_technician_name:"",wagon_numbers:"",invoice_number:"",fuel_consumption_note:""};
const NUMERIC=["sa_percent","alpha","wa_percent","aa_percent","wr_percent","hydrogen_input_percent","qb_a_1_kcal_kg","qb_a_2_kcal_kg","va_percent"];
const REQUIRED=["sample_date","sample_name","calorimeter",...NUMERIC,"lab_technician_name"];
const LABEL:Record<Status,string>={DRAFT:"Черновик",COMPLETED:"Завершён",ARCHIVED:"Архив"};
const CALC_LABEL:Record<string,string>={qb_a_kcal_kg:"Qb_a",qs_a_kcal_kg:"Qs_a",ad_percent:"Ad",ar_percent:"Ar",vdaf_percent:"Vdaf",vr_percent:"Vr",sr_percent:"Sr",sd_percent:"Sd",qs_r_kcal_kg:"Qs_r",qi_a_kcal_kg:"Qi_a",hr_percent:"Hr",qi_r_kcal_kg:"Qi_r",qs_daf_kcal_kg:"Qs_daf",wmax_daf_percent:"Wmax_daf",qs_af_kcal_kg:"Qs_af",qb_daf_kcal_kg:"Qb_daf"};
const normalize=(value:string)=>{const clean=value.replace(",",".").replace(/[^0-9.]/g,"");const [a,...b]=clean.split(".");return b.length?`${a}.${b.join("")}`:a;};
const densityUiUrl=(import.meta.env.VITE_LAB_UI_URL as string|undefined)?.replace(/\/$/,"")||"http://localhost:5174";

export function LaboratoryPage(){
 const [tab,setTab]=useState<"density"|"fuel">("fuel"),[items,setItems]=useState<Item[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState<Item|null>(null),[form,setForm]=useState<Form>({...EMPTY}),[saved,setSaved]=useState(JSON.stringify(EMPTY)),[calculated,setCalculated]=useState<Record<string,string>>({}),[error,setError]=useState(""),[loading,setLoading]=useState(false),[page,setPage]=useState(0);
 const [filters,setFilters]=useState({date_from:"",date_to:"",status:"",search:""});const first=useRef<HTMLInputElement>(null);const dirty=selected!==null&&JSON.stringify(form)!==saved;const readonly=selected?.status!=="DRAFT";const completed=REQUIRED.filter(x=>form[x]?.trim()).length;
 const load=async()=>{setLoading(true);try{const p=new URLSearchParams({limit:"25",offset:String(page*25)});Object.entries(filters).forEach(([k,v])=>v&&p.set(k,v));const r=await fetch(`/api/v1/laboratory/fuel-quality?${p}`);if(!r.ok)throw new Error();const d=await r.json();setItems(d.items);setTotal(d.total);setError("");}catch{setError("Не удалось загрузить журнал лаборатории.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[filters,page]);
 useEffect(()=>{if(readonly||NUMERIC.some(x=>!form[x])){if(!readonly)setCalculated({});return;}const timer=setTimeout(async()=>{try{const body=Object.fromEntries(NUMERIC.map(x=>[x,form[x]]));const r=await fetch("/api/v1/laboratory/fuel-quality/calculate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(typeof d.detail==="string"?d.detail:"Проверьте исходные значения");setCalculated(d);setError("");}catch(e){setCalculated({});setError(e instanceof Error?e.message:"Ошибка расчёта");}},250);return()=>clearTimeout(timer);},[form,readonly]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};const nav=(e:Event)=>{if(dirty&&!confirm("Есть несохранённые изменения.\nПродолжить без сохранения?"))e.preventDefault();};addEventListener("beforeunload",before);addEventListener("app:navigate",nav);return()=>{removeEventListener("beforeunload",before);removeEventListener("app:navigate",nav);};},[dirty]);
 const open=(item:Item)=>{if(dirty&&!confirm("Есть несохранённые изменения.\nПродолжить без сохранения?"))return;const next=Object.fromEntries(Object.keys(EMPTY).map(x=>[x,String((item as unknown as Record<string,unknown>)[x]??"")]));setSelected(item);setForm(next);setSaved(JSON.stringify(next));setCalculated(item.calculated);setTimeout(()=>first.current?.focus());};
 const createNew=()=>{if(dirty&&!confirm("Есть несохранённые изменения.\nПродолжить без сохранения?"))return;setSelected({id:0,status:"DRAFT",updated_at:"",sample_date:"",sample_name:"",calorimeter:"",wr_percent:"",wa_percent:"",aa_percent:"",sa_percent:"",va_percent:"",calculated:{}});setForm({...EMPTY});setSaved(JSON.stringify(EMPTY));setCalculated({});setTimeout(()=>first.current?.focus());};
 const save=async(complete=false)=>{if(!selected||readonly)return;setLoading(true);try{const payload={...form,...(selected.id?{expected_updated_at:selected.updated_at}:{})};let r=await fetch(selected.id?`/api/v1/laboratory/fuel-quality/${selected.id}`:"/api/v1/laboratory/fuel-quality",{method:selected.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(r.status===409)throw new Error("Анализ был изменён другим пользователем. Обновите карточку.");const detail=await r.json();if(!r.ok)throw new Error(typeof detail.detail==="string"?detail.detail:"Проверьте обязательные поля");let next=detail;if(complete){r=await fetch(`/api/v1/laboratory/fuel-quality/${next.id}/complete`,{method:"POST"});next=await r.json();if(!r.ok)throw new Error(next.detail||"Не удалось завершить анализ");}const nextForm=Object.fromEntries(Object.keys(EMPTY).map(x=>[x,String(next[x]??"")]));setSelected(next);setForm(nextForm);setSaved(JSON.stringify(nextForm));setCalculated(next.calculated);setError("");await load();}catch(e){setError(e instanceof Error?e.message:"Ошибка сохранения");}finally{setLoading(false);}};
 const input=(key:string,title:string,unit="")=><label>{title}{REQUIRED.includes(key)&&<span className="required"> *</span>}<span className="unit-input"><input ref={key==="sample_date"?first:undefined} disabled={readonly} type={key==="sample_date"?"date":"text"} value={form[key]} onChange={e=>setForm({...form,[key]:NUMERIC.includes(key)?normalize(e.target.value):e.target.value})}/>{unit&&<small>{unit}</small>}</span></label>;
 const updateFilter=(key:string,value:string)=>{setPage(0);setFilters(x=>({...x,[key]:value}));};
 const journal=useMemo(()=>items,[items]);
 return <main className="laboratory-page"><div className="acceptance-heading"><div><h1>Лаборатория</h1><p>Исследования и ежесуточный журнал топлива</p></div></div><div className="laboratory-tabs"><button className={tab==="density"?"active":""} onClick={()=>setTab("density")}>Насыпная плотность</button><button className={tab==="fuel"?"active":""} onClick={()=>setTab("fuel")}>Ежесуточный контроль топлива</button></div>
 {tab==="density"?<section className="laboratory-density acceptance-card"><h2>Насыпная плотность</h2><p>Существующий независимый процесс исследований плотности сохранён без изменений.</p><a className="primary-action" href={`${densityUiUrl}/experiments`}>Открыть журнал насыпной плотности</a></section>:<>
 <section className="acceptance-toolbar laboratory-filters"><label>Дата с<input type="date" value={filters.date_from} onChange={e=>updateFilter("date_from",e.target.value)}/></label><label>Дата по<input type="date" value={filters.date_to} onChange={e=>updateFilter("date_to",e.target.value)}/></label><label>Статус<select value={filters.status} onChange={e=>updateFilter("status",e.target.value)}><option value="">Все</option><option value="DRAFT">Черновик</option><option value="COMPLETED">Завершён</option><option value="ARCHIVED">Архив</option></select></label><label>Поиск<input value={filters.search} onChange={e=>updateFilter("search",e.target.value)} placeholder="Проба, накладная, вагоны"/></label><button className="primary-action" onClick={createNew}>Новый анализ</button><a className="primary-action" href={`/api/v1/laboratory/fuel-quality/export.xlsx?year=${new Date().getFullYear()}&month=${new Date().getMonth()+1}`}>Excel</a></section>
 {error&&<div className="acceptance-alert error">{error} <button onClick={()=>void load()}>Повторить</button></div>}<section className="acceptance-work laboratory-work"><div><div className="acceptance-table-wrap"><table className="acceptance-table"><thead><tr><th>Дата</th><th>Проба</th><th>Wr</th><th>Ar</th><th>Ad</th><th>Vdaf</th><th>Sa</th><th>Qir</th><th>Статус</th></tr></thead><tbody>{journal.map(x=><tr key={x.id} onClick={()=>open(x)}><td>{new Date(`${x.sample_date}T00:00:00`).toLocaleDateString("ru-RU")}</td><td>{x.sample_name}</td><td>{x.wr_percent}</td><td>{x.calculated.ar_percent}</td><td>{x.calculated.ad_percent}</td><td>{x.calculated.vdaf_percent}</td><td>{x.sa_percent}</td><td>{x.calculated.qi_r_kcal_kg}</td><td><span className={`acceptance-status ${x.status.toLowerCase()}`}>{LABEL[x.status]}</span></td></tr>)}</tbody></table>{!loading&&!items.length&&<div className="acceptance-empty">Анализов не найдено.</div>}</div><div className="acceptance-pagination"><button disabled={!page} onClick={()=>setPage(x=>x-1)}>Назад</button><span>Страница {page+1}</span><button disabled={(page+1)*25>=total} onClick={()=>setPage(x=>x+1)}>Далее</button></div></div>
 {selected&&<form className="acceptance-card fuel-card" onSubmit={e=>e.preventDefault()}><div className="card-title"><h2>{selected.id?selected.sample_name:"Новый анализ"}</h2><span className={`acceptance-status ${selected.status.toLowerCase()}`}>{LABEL[selected.status]}</span></div><section><h3>Исходные данные</h3><div className="acceptance-fields">{input("sample_date","Дата пробы")}{input("sample_name","Наименование пробы")}{input("calorimeter","Калориметр")}{input("sa_percent","Sa","%")}{input("alpha","alpha")}{input("wa_percent","Wa","%")}{input("aa_percent","Aa","%")}{input("wr_percent","Wr","%")}{input("hydrogen_input_percent","H (исходное поле PDF)","%")}{input("qb_a_1_kcal_kg","Qb(1)","ккал/кг")}{input("qb_a_2_kcal_kg","Qb(2)","ккал/кг")}{input("va_percent","Va","%")}{input("lab_technician_name","Лаборант")}{input("wagon_numbers","№ вагонов")}{input("invoice_number","№ накладной")}<label>Расход топлива / примечание<textarea disabled={readonly} value={form.fuel_consumption_note} onChange={e=>setForm({...form,fuel_consumption_note:e.target.value})}/></label></div></section><section><h3>Расчётные показатели</h3><div className="fuel-results">{Object.entries(CALC_LABEL).map(([key,title])=><span key={key}><small>{title}</small><b>{calculated[key]??"—"}</b><em>{key.includes("kcal")?"ккал/кг":"%"}</em></span>)}</div></section><section><h3>Итог для ежесуточного журнала</h3><div className="fuel-journal-summary">{[["Wr",form.wr_percent],["Wa",form.wa_percent],["Aa",form.aa_percent],["Ar",calculated.ar_percent],["Ad",calculated.ad_percent],["Va",form.va_percent],["Vdaf",calculated.vdaf_percent],["Vr",calculated.vr_percent],["Sa",form.sa_percent],["Sr",calculated.sr_percent],["Sd",calculated.sd_percent],["Qir",calculated.qi_r_kcal_kg]].map(([k,v])=><span key={k}><small>{k}</small><b>{v||"—"}</b></span>)}</div></section>{!readonly&&<div className="acceptance-actions"><button disabled={loading} type="button" onClick={()=>void save(false)}>Сохранить черновик</button><button disabled={loading||completed<REQUIRED.length||!calculated.qi_r_kcal_kg} type="button" className="primary-action" onClick={()=>void save(true)}>Завершить анализ</button></div>}</form>}</section></>}</main>;
}
