import { useEffect, useState } from "react";
import { labApi } from "../api";
import { ErrorBanner, Loading } from "../components/Ui";
import type { CoalFraction, CoalGrade, Supplier } from "../types";

export function DirectoriesPage() {
  const [grades, setGrades] = useState<CoalGrade[]>([]); const [fractions, setFractions] = useState<CoalFraction[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [grade, setGrade] = useState({ code: "", name: "", description: "" }); const [fraction, setFraction] = useState({ name: "", min: "", max: "" }); const [supplier, setSupplier] = useState({ code: "", name: "" });
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = () => { setLoading(true); Promise.all([labApi.grades(), labApi.fractions(), labApi.suppliers()]).then(([g, f, s]) => { setGrades(g); setFractions(f); setSuppliers(s); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []);
  const run = async (request: Promise<unknown>, reset: () => void) => { setError(null); try { await request; reset(); load(); } catch (e) { setError((e as Error).message); } };
  if (loading && !grades.length && !fractions.length && !suppliers.length) return <Loading />;
  return <><div className="page-heading"><div><p className="eyebrow">Настройки</p><h1>Справочники</h1><p>Значения, используемые при регистрации лабораторных исследований.</p></div></div><ErrorBanner message={error} />
    <div className="directory-grid">
      <section className="panel directory"><div className="panel-title"><div><h2>Марки угля</h2><span>{grades.length} записей</span></div></div><form onSubmit={(e) => { e.preventDefault(); run(labApi.createGrade(grade), () => setGrade({ code: "", name: "", description: "" })); }}><div className="inline-fields"><input required placeholder="Код" value={grade.code} onChange={(e) => setGrade({ ...grade, code: e.target.value })} /><input required placeholder="Наименование" value={grade.name} onChange={(e) => setGrade({ ...grade, name: e.target.value })} /></div><input placeholder="Описание" value={grade.description} onChange={(e) => setGrade({ ...grade, description: e.target.value })} /><button className="button primary small">Добавить марку</button></form><div className="directory-list">{grades.map((x) => <div key={x.id}><span><b>{x.code}</b>{x.name}</span><i className={x.is_active ? "active-dot" : "inactive-dot"}>{x.is_active ? "Активна" : "Неактивна"}</i></div>)}</div></section>
      <section className="panel directory"><div className="panel-title"><div><h2>Фракции</h2><span>{fractions.length} записей</span></div></div><form onSubmit={(e) => { e.preventDefault(); run(labApi.createFraction({ name: fraction.name, min_size_mm: fraction.min ? Number(fraction.min) : undefined, max_size_mm: fraction.max ? Number(fraction.max) : undefined }), () => setFraction({ name: "", min: "", max: "" })); }}><input required placeholder="Наименование" value={fraction.name} onChange={(e) => setFraction({ ...fraction, name: e.target.value })} /><div className="inline-fields"><input type="number" min="0" placeholder="От, мм" value={fraction.min} onChange={(e) => setFraction({ ...fraction, min: e.target.value })} /><input type="number" min="0" placeholder="До, мм" value={fraction.max} onChange={(e) => setFraction({ ...fraction, max: e.target.value })} /></div><button className="button primary small">Добавить фракцию</button></form><div className="directory-list">{fractions.map((x) => <div key={x.id}><span><b>{x.name}</b>{x.min_size_mm ?? "—"}–{x.max_size_mm ?? "—"} мм</span><i className={x.is_active ? "active-dot" : "inactive-dot"}>{x.is_active ? "Активна" : "Неактивна"}</i></div>)}</div></section>
      <section className="panel directory"><div className="panel-title"><div><h2>Поставщики</h2><span>{suppliers.length} записей</span></div></div><form onSubmit={(e) => { e.preventDefault(); run(labApi.createSupplier({ code: supplier.code || undefined, name: supplier.name }), () => setSupplier({ code: "", name: "" })); }}><div className="inline-fields"><input placeholder="Код" value={supplier.code} onChange={(e) => setSupplier({ ...supplier, code: e.target.value })} /><input required placeholder="Наименование" value={supplier.name} onChange={(e) => setSupplier({ ...supplier, name: e.target.value })} /></div><button className="button primary small">Добавить поставщика</button></form><div className="directory-list">{suppliers.map((x) => <div key={x.id}><span><b>{x.name}</b>{x.code || "Без кода"}</span><i className={x.is_active ? "active-dot" : "inactive-dot"}>{x.is_active ? "Активен" : "Неактивен"}</i></div>)}</div></section>
    </div></>;
}
