import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { labApi } from "../api";
import { ErrorBanner, formatDate, formatDensity, Loading, StatusBadge } from "../components/Ui";
import type { AuditEntry, CoalFraction, CoalGrade, Experiment, Supplier } from "../types";

const actionLabels: Record<string, string> = { EXPERIMENT_CREATED: "Исследование создано", EXPERIMENT_UPDATED: "Данные изменены", MEASUREMENT_ADDED: "Добавлено измерение", MEASUREMENT_UPDATED: "Измерение изменено", MEASUREMENT_DELETED: "Измерение удалено", COMPLETED: "Исследование завершено", ARCHIVED: "Исследование архивировано" };

export function ExperimentDetailsPage() {
  const id = Number(useParams().id); const navigate = useNavigate();
  const [item, setItem] = useState<Experiment | null>(null); const [audit, setAudit] = useState<AuditEntry[]>([]);
  const [names, setNames] = useState({ grade: "—", fraction: "—", supplier: "—" }); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = () => Promise.all([labApi.experiment(id), labApi.audit(id), labApi.grades(), labApi.fractions(), labApi.suppliers()]).then(([experiment, log, grades, fractions, suppliers]) => { setItem(experiment); setAudit(log); setNames({ grade: grades.find((x: CoalGrade) => x.id === experiment.coal_grade_id)?.name || "—", fraction: fractions.find((x: CoalFraction) => x.id === experiment.coal_fraction_id)?.name || "—", supplier: suppliers.find((x: Supplier) => x.id === experiment.supplier_id)?.name || "—" }); }).catch((e) => setError(e.message));
  useEffect(() => { load(); }, [id]);
  const action = async (type: "complete" | "archive") => { const question = type === "complete" ? "Завершить исследование? После этого редактирование будет недоступно." : "Архивировать исследование?"; if (!confirm(question)) return; setBusy(true); setError(null); try { type === "complete" ? await labApi.complete(id) : await labApi.archive(id); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  if (!item && !error) return <Loading />;
  if (!item) return <ErrorBanner message={error} />;
  return <>
    <div className="page-heading"><div><p className="eyebrow">Карточка исследования</p><h1>{item.experiment_number}</h1><p>Создано {formatDate(item.created_at, true)} · обновлено {formatDate(item.updated_at, true)}</p></div><div className="heading-actions"><Link className="button secondary" to="/experiments">К журналу</Link>{item.status === "DRAFT" && <Link className="button secondary" to={`/experiments/${id}/edit`}>Редактировать</Link>}{item.status === "DRAFT" && <button disabled={busy} className="button primary" onClick={() => action("complete")}>Завершить</button>}{item.status !== "ARCHIVED" && <button disabled={busy} className="button danger" onClick={() => action("archive")}>В архив</button>}</div></div>
    <ErrorBanner message={error} />
    <div className="details-grid"><section className="panel form-section"><div className="panel-title"><div><h2>Основные сведения</h2><span>Идентификация и происхождение пробы</span></div><StatusBadge status={item.status} /></div><dl className="data-grid"><div><dt>Марка угля</dt><dd>{names.grade}</dd></div><div><dt>Фракция</dt><dd>{names.fraction}</dd></div><div><dt>Поставщик</dt><dd>{names.supplier}</dd></div><div><dt>Партия</dt><dd>{item.batch_number || "—"}</dd></div><div><dt>Накладная</dt><dd>{item.invoice_number || "—"}</dd></div><div><dt>Лаборант</dt><dd>{item.laboratory_user_name}</dd></div><div><dt>Отбор пробы</dt><dd>{formatDate(item.sampled_at, true)}</dd></div><div><dt>Анализ</dt><dd>{formatDate(item.tested_at, true)}</dd></div><div><dt>Рабочая влажность</dt><dd>{item.moisture_percent == null ? "—" : `${item.moisture_percent}%`}</dd></div><div className="span-2"><dt>Комментарий</dt><dd>{item.comment || "—"}</dd></div></dl></section>
      <aside className="result-card"><span>Итог исследования</span><strong>{formatDensity(item.average_density_kg_m3)}</strong><p>Средняя насыпная плотность</p><div><b>{item.included_measurements_count}</b><small>включено</small><b>{item.measurements.length - item.included_measurements_count}</b><small>исключено</small></div></aside></div>
    <section className="panel table-panel"><div className="panel-title"><div><h2>Измерения</h2><span>Все исходные и рассчитанные значения</span></div></div><div className="table-scroll"><table><thead><tr><th>№</th><th>Объём</th><th>Масса угля</th><th>Плотность</th><th>В среднем</th><th>Причина исключения</th></tr></thead><tbody>{item.measurements.map((m) => <tr className={!m.is_included ? "excluded" : ""} key={m.id}><td>{m.sequence_number}</td><td>{m.entered_volume_value} {m.entered_volume_unit === "LITER" ? "л" : "м³"}</td><td>{m.material_mass_kg} кг</td><td><strong>{formatDensity(m.calculated_density_kg_m3)}</strong></td><td>{m.is_included ? "Да" : "Нет"}</td><td>{m.exclusion_reason || "—"}</td></tr>)}</tbody></table></div></section>
    <section className="panel audit"><div className="panel-title"><div><h2>История действий</h2><span>Хронология изменений исследования</span></div></div>{audit.map((entry) => <div className="audit-row" key={entry.id}><span className="audit-dot" /><div><strong>{actionLabels[entry.action] || entry.action}</strong><p>{entry.changed_by_name || "Система"}</p></div><time>{formatDate(entry.created_at, true)}</time></div>)}</section>
  </>;
}
