import {FormEvent,useEffect,useState} from "react";
import "./supplierAdmin.css";

type Tab="suppliers"|"vehicles"|"grades"|"specs";
type Page<T>={items:T[];total:number;page:number;page_size:number;total_pages:number};
type Supplier={id:number;name:string;short_name?:string;inn?:string;comment?:string;is_active:boolean};
type Vehicle={id:number;registration_number:string;make_model?:string;comment?:string;current_supplier_name?:string;is_active:boolean};
type Grade={id:number;code:string;name:string;description?:string;is_active:boolean};
type Fraction={fraction_min_mm:string;fraction_max_mm:string;operator:string;value:string;unit:string};
type Spec={id:number;supplier_id:number;coal_grade_id:number;supplier_name:string;coal_grade_name:string;calorific_value?:string;calorific_value_unit:string;moisture_pct?:string;ash_pct?:string;valid_from:string;valid_to?:string;comment?:string;is_active:boolean;fractions:Fraction[]};
const EMPTY={items:[],total:0,page:1,page_size:20,total_pages:0};

async function api<T>(url:string,init?:RequestInit):Promise<T>{
 const response=await fetch(url,init);if(response.ok)return response.status===204?undefined as T:response.json();
 const body=await response.json().catch(()=>({detail:"Ошибка API"}));throw body;
}
const json=(method:string,body:unknown)=>({method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
const messageOf=(reason:any)=>typeof reason?.detail==="string"?reason.detail:reason?.detail?.message||"Не удалось выполнить операцию";
const decimalPattern=/^\d+(?:[.,]\d+)?$/;
const decimalValue=(value:string,field:string,optional=false)=>{const clean=value.trim();if(optional&&!clean)return null;if(!decimalPattern.test(clean))throw new Error(`${field}: введите неотрицательное число, например 13,5 или 13.5`);return clean.replace(",",".")};
const displayDecimal=(value:string|undefined)=>{if(!value)return value;const [whole,fraction]=String(value).split(".");const trimmed=fraction?.replace(/0+$/,"");return trimmed?`${whole}.${trimmed}`:whole};

export function SupplierAdminPage(){
 const [tab,setTab]=useState<Tab>("suppliers"),[page,setPage]=useState(1),[search,setSearch]=useState(""),[active,setActive]=useState(""),[loading,setLoading]=useState(false);
 const [data,setData]=useState<Page<any>>(EMPTY),[suppliers,setSuppliers]=useState<Supplier[]>([]),[grades,setGrades]=useState<Grade[]>([]),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const [selectedSupplier,setSelectedSupplier]=useState<Supplier|null>(null),[selectedVehicle,setSelectedVehicle]=useState<Vehicle|null>(null),[selectedGrade,setSelectedGrade]=useState<Grade|null>(null),[selectedSpec,setSelectedSpec]=useState<Spec|null>(null),[newVersion,setNewVersion]=useState(false);
 const [supplierForm,setSupplierForm]=useState({name:"",short_name:"",inn:"",comment:""});
 const [vehicleForm,setVehicleForm]=useState({registration_number:"",make_model:"",supplier_id:"",comment:""});
 const [gradeForm,setGradeForm]=useState({code:"",name:"",description:""});
 const [specForm,setSpecForm]=useState({supplier_id:"",coal_grade_id:"",calorific_value:"",moisture_pct:"",ash_pct:"",valid_from:new Date().toISOString().slice(0,10),fraction_min_mm:"0",fraction_max_mm:"5",operator:"<=",fraction_value:"40"});

 const load=async()=>{setLoading(true);setError("");try{
  const endpoint={suppliers:"suppliers",vehicles:"vehicles",grades:"coal-grades",specs:"coal-specs"}[tab];
  const query=new URLSearchParams({page:String(page),page_size:"20"});if(search&&(tab==="suppliers"||tab==="vehicles"))query.set("search",search);if(active)query.set("is_active",active);
  const [rows,s,g]=await Promise.all([api<Page<any>>(`/api/admin/${endpoint}?${query}`),api<Page<Supplier>>("/api/admin/suppliers?page_size=100&is_active=true"),api<Page<Grade>>("/api/admin/coal-grades?page_size=200")]);
  setData(rows);setSuppliers(s.items);setGrades(g.items);
  if(page>1&&page>rows.total_pages)setPage(Math.max(1,rows.total_pages));
 }catch(reason){setError(messageOf(reason))}finally{setLoading(false)}};
 useEffect(()=>{load()},[tab,page,search,active]);
 const feedback=(text:string)=>{setSuccess(text);setError("");setTimeout(()=>setSuccess(""),2500)};

 const saveSupplier=async(e:FormEvent)=>{e.preventDefault();try{await api(selectedSupplier?`/api/admin/suppliers/${selectedSupplier.id}`:"/api/admin/suppliers",json(selectedSupplier?"PATCH":"POST",supplierForm));feedback("Поставщик сохранён.");setSelectedSupplier(null);setSupplierForm({name:"",short_name:"",inn:"",comment:""});await load()}catch(r){setError(messageOf(r))}};
 const selectSupplier=(item:Supplier)=>{setSelectedSupplier(item);setSupplierForm({name:item.name,short_name:item.short_name||"",inn:item.inn||"",comment:item.comment||""})};
 const deleteSupplier=async(item:Supplier)=>{if(!confirm(`Удалить поставщика «${item.name}»?\n\nДействие возможно только если поставщик ещё не используется в системе.`))return;try{await api(`/api/admin/suppliers/${item.id}`,{method:"DELETE"});feedback("Поставщик удалён.");setSelectedSupplier(null);await load()}catch(r:any){const refs=r?.detail?.references;setError(`${messageOf(r)}${refs?` Машины: ${refs.vehicles}; характеристики угля: ${refs.coal_specs}; лабораторные исследования: ${refs.laboratory_records}.`:""}`)}};
 const toggleSupplier=async(item:Supplier)=>{try{await api(`/api/admin/suppliers/${item.id}`,json("PATCH",{is_active:!item.is_active}));feedback(item.is_active?"Поставщик деактивирован.":"Поставщик активирован.");await load()}catch(r){setError(messageOf(r))}};

 const saveGrade=async(e:FormEvent)=>{e.preventDefault();try{await api(selectedGrade?`/api/admin/coal-grades/${selectedGrade.id}`:"/api/admin/coal-grades",json(selectedGrade?"PATCH":"POST",gradeForm));feedback("Марка угля сохранена.");setSelectedGrade(null);setGradeForm({code:"",name:"",description:""});await load()}catch(r){setError(messageOf(r))}};
 const selectGrade=(item:Grade)=>{setSelectedGrade(item);setGradeForm({code:item.code,name:item.name,description:item.description||""})};
 const toggleGrade=async(item:Grade)=>{try{await api(`/api/admin/coal-grades/${item.id}`,json("PATCH",{is_active:!item.is_active}));feedback(item.is_active?"Марка деактивирована.":"Марка активирована.");await load()}catch(r){setError(messageOf(r))}};
 const deleteGrade=async(item:Grade)=>{if(!confirm(`Удалить марку угля «${item.code}»?`))return;try{await api(`/api/admin/coal-grades/${item.id}`,{method:"DELETE"});feedback("Марка угля удалена.");setSelectedGrade(null);await load()}catch(r){setError(messageOf(r))}};

 const selectVehicle=(item:Vehicle)=>{setSelectedVehicle(item);setVehicleForm({registration_number:item.registration_number,make_model:item.make_model||"",supplier_id:"",comment:item.comment||""})};
 const resetVehicle=()=>{setSelectedVehicle(null);setVehicleForm({registration_number:"",make_model:"",supplier_id:"",comment:""})};
 const saveVehicle=async(e:FormEvent)=>{e.preventDefault();try{if(selectedVehicle)await api(`/api/admin/vehicles/${selectedVehicle.id}`,json("PATCH",{registration_number:vehicleForm.registration_number,make_model:vehicleForm.make_model,comment:vehicleForm.comment}));else await api("/api/admin/vehicles",json("POST",{...vehicleForm,supplier_id:Number(vehicleForm.supplier_id)}));feedback("Машина сохранена.");resetVehicle();await load()}catch(r){setError(messageOf(r))}};
 const deleteVehicle=async(item:Vehicle)=>{if(!confirm(`Удалить машину «${item.registration_number}»?`))return;try{await api(`/api/admin/vehicles/${item.id}`,{method:"DELETE"});feedback("Машина удалена.");resetVehicle();await load()}catch(r){setError(messageOf(r))}};
 const specPayload=()=>({supplier_id:Number(specForm.supplier_id),coal_grade_id:Number(specForm.coal_grade_id),calorific_value:decimalValue(specForm.calorific_value,"Калорийность",true),calorific_value_unit:"kcal/kg",moisture_pct:decimalValue(specForm.moisture_pct,"Влага",true),ash_pct:decimalValue(specForm.ash_pct,"Зола",true),valid_from:specForm.valid_from,fractions:[{fraction_min_mm:decimalValue(specForm.fraction_min_mm,"Минимум фракции"),fraction_max_mm:decimalValue(specForm.fraction_max_mm,"Максимум фракции"),operator:specForm.operator,value:decimalValue(specForm.fraction_value,"Содержание фракции"),unit:"%"}]});
 const selectSpec=(item:Spec,version=false)=>{setSelectedSpec(item);setNewVersion(version);const f=item.fractions[0];setSpecForm({supplier_id:String(item.supplier_id),coal_grade_id:String(item.coal_grade_id),calorific_value:displayDecimal(item.calorific_value)||"",moisture_pct:displayDecimal(item.moisture_pct)||"",ash_pct:displayDecimal(item.ash_pct)||"",valid_from:version?new Date().toISOString().slice(0,10):item.valid_from,fraction_min_mm:displayDecimal(f?.fraction_min_mm)||"0",fraction_max_mm:displayDecimal(f?.fraction_max_mm)||"5",operator:f?.operator||"<=",fraction_value:displayDecimal(f?.value)||"40"})};
 const resetSpec=()=>{setSelectedSpec(null);setNewVersion(false);setSpecForm({...specForm,supplier_id:"",coal_grade_id:"",calorific_value:"",moisture_pct:"",ash_pct:"",valid_from:new Date().toISOString().slice(0,10)})};
 const saveSpec=async(e:FormEvent)=>{e.preventDefault();try{const url=!selectedSpec?"/api/admin/coal-specs":newVersion?`/api/admin/coal-specs/${selectedSpec.id}/replace`:`/api/admin/coal-specs/${selectedSpec.id}`;await api(url,json(selectedSpec&&!newVersion?"PATCH":"POST",specPayload()));feedback(newVersion?"Новая версия создана.":"Спецификация сохранена.");resetSpec();await load()}catch(r){setError(r instanceof Error?r.message:messageOf(r))}};
 const deleteSpec=async(item:Spec)=>{if(!confirm("Удалить характеристику угля?"))return;try{await api(`/api/admin/coal-specs/${item.id}`,{method:"DELETE"});feedback("Спецификация удалена.");resetSpec();await load()}catch(r){setError(messageOf(r))}};

 const pager=<div className="admin-pager"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Назад</button><span>Страница {data.page} из {data.total_pages||1}</span><button disabled={page>=data.total_pages} onClick={()=>setPage(v=>v+1)}>Далее</button></div>;
 return <main className="supplier-admin"><h1>Администрирование</h1><p>Поставщики, машины и заявленные характеристики угля</p>
  <nav className="admin-tabs"><button className={tab==="suppliers"?"active":""} onClick={()=>{setTab("suppliers");setPage(1)}}>Поставщики</button><button className={tab==="vehicles"?"active":""} onClick={()=>{setTab("vehicles");setPage(1)}}>Машины</button><button className={tab==="grades"?"active":""} onClick={()=>{setTab("grades");setPage(1)}}>Марки угля</button><button className={tab==="specs"?"active":""} onClick={()=>{setTab("specs");setPage(1)}}>Характеристики угля</button></nav>
  <div className="admin-toolbar"><input aria-label="Поиск" placeholder="Поиск" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Статус" value={active} onChange={e=>setActive(e.target.value)}><option value="">Все статусы</option><option value="true">Активные</option><option value="false">Неактивные</option></select></div>
  {error&&<div className="admin-error">{error}</div>}{success&&<div className="admin-success">{success}</div>}
  <div className="admin-grid"><section className="admin-panel">{loading?<p>Загрузка…</p>:<>{tab==="suppliers"&&<table><thead><tr><th>ID / Наименование</th><th>ИНН</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{(data.items as Supplier[]).map(x=><tr key={x.id}><td><small>#{x.id}</small>{x.name}</td><td>{x.inn||"—"}</td><td>{x.is_active?"Активен":"Неактивен"}</td><td><button onClick={()=>selectSupplier(x)}>Редактировать</button><button onClick={()=>toggleSupplier(x)}>{x.is_active?"Деактивировать":"Активировать"}</button><button className="danger" onClick={()=>deleteSupplier(x)}>Удалить</button></td></tr>)}</tbody></table>}
  {tab==="vehicles"&&<table><thead><tr><th>ID / Госномер</th><th>Марка / модель</th><th>Текущий поставщик</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{(data.items as Vehicle[]).map(x=><tr key={x.id}><td><small>#{x.id}</small><b>{x.registration_number}</b></td><td>{x.make_model||"—"}</td><td>{x.current_supplier_name||"—"}</td><td>{x.is_active?"Активна":"Неактивна"}</td><td><button onClick={()=>selectVehicle(x)}>Редактировать</button><button className="danger" onClick={()=>deleteVehicle(x)}>Удалить</button></td></tr>)}</tbody></table>}
  {tab==="grades"&&<table><thead><tr><th>ID / Марка</th><th>Описание</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{(data.items as Grade[]).map(x=><tr key={x.id}><td><small>#{x.id}</small>{x.code}</td><td>{x.description||x.name}</td><td>{x.is_active?"Активна":"Неактивна"}</td><td><button onClick={()=>selectGrade(x)}>Редактировать</button><button onClick={()=>toggleGrade(x)}>{x.is_active?"Деактивировать":"Активировать"}</button><button className="danger" onClick={()=>deleteGrade(x)}>Удалить</button></td></tr>)}</tbody></table>}
  {tab==="specs"&&<table><thead><tr><th>ID / Поставщик / марка</th><th>Калорийность</th><th>Влага / зола</th><th>Период</th><th>Действия</th></tr></thead><tbody>{(data.items as Spec[]).map(x=><tr key={x.id}><td><small>#{x.id}</small><b>{x.supplier_name}</b><small>{x.coal_grade_name}</small></td><td>{x.calorific_value?`${displayDecimal(x.calorific_value)} ${x.calorific_value_unit}`:"—"}</td><td>{displayDecimal(x.moisture_pct)||"—"}% / {displayDecimal(x.ash_pct)||"—"}%</td><td>{x.valid_from} — {x.valid_to||"текущая"}</td><td><button onClick={()=>selectSpec(x)}>Редактировать</button><button onClick={()=>selectSpec(x,true)}>Новая версия</button><button className="danger" onClick={()=>deleteSpec(x)}>Удалить</button></td></tr>)}</tbody></table>}
  {!data.items.length&&<p className="admin-empty">Записей не найдено</p>}{pager}</>}</section>
  {tab==="suppliers"&&<form className="admin-panel admin-form" onSubmit={saveSupplier}><h2>{selectedSupplier?"Редактировать поставщика":"Новый поставщик"}</h2><label>Наименование<input required value={supplierForm.name} onChange={e=>setSupplierForm({...supplierForm,name:e.target.value})}/></label><label>Краткое имя<input value={supplierForm.short_name} onChange={e=>setSupplierForm({...supplierForm,short_name:e.target.value})}/></label><label>ИНН<input value={supplierForm.inn} onChange={e=>setSupplierForm({...supplierForm,inn:e.target.value})}/></label><label>Комментарий<textarea value={supplierForm.comment} onChange={e=>setSupplierForm({...supplierForm,comment:e.target.value})}/></label><button className="primary-action">{selectedSupplier?"Сохранить изменения":"Добавить"}</button>{selectedSupplier&&<button type="button" onClick={()=>{setSelectedSupplier(null);setSupplierForm({name:"",short_name:"",inn:"",comment:""})}}>Отмена</button>}</form>}
  {tab==="vehicles"&&<form className="admin-panel admin-form" onSubmit={saveVehicle}><h2>{selectedVehicle?"Редактировать машину":"Новая машина"}</h2><label>Госномер<input required value={vehicleForm.registration_number} onChange={e=>setVehicleForm({...vehicleForm,registration_number:e.target.value})}/></label><label>Марка / модель<input value={vehicleForm.make_model} onChange={e=>setVehicleForm({...vehicleForm,make_model:e.target.value})}/></label>{!selectedVehicle&&<label>Поставщик<select required value={vehicleForm.supplier_id} onChange={e=>setVehicleForm({...vehicleForm,supplier_id:e.target.value})}><option value="">Выберите</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<button className="primary-action">{selectedVehicle?"Сохранить изменения":"Добавить"}</button>{selectedVehicle&&<button type="button" onClick={resetVehicle}>Отмена</button>}</form>}
  {tab==="grades"&&<form className="admin-panel admin-form" onSubmit={saveGrade}><h2>{selectedGrade?"Редактировать марку":"Добавить марку угля"}</h2><label>Марка угля *<input required value={gradeForm.code} onChange={e=>setGradeForm({...gradeForm,code:e.target.value,name:e.target.value})}/></label><label>Описание<textarea value={gradeForm.description} onChange={e=>setGradeForm({...gradeForm,description:e.target.value})}/></label><button className="primary-action">{selectedGrade?"Сохранить изменения":"Добавить"}</button>{selectedGrade&&<button type="button" onClick={()=>{setSelectedGrade(null);setGradeForm({code:"",name:"",description:""})}}>Отмена</button>}</form>}
  {tab==="specs"&&<form className="admin-panel admin-form" onSubmit={saveSpec}><h2>{!selectedSpec?"Новая спецификация":newVersion?"Новая версия спецификации":"Редактировать спецификацию"}</h2><label>Поставщик<select required value={specForm.supplier_id} onChange={e=>setSpecForm({...specForm,supplier_id:e.target.value})}><option value="">Выберите</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Марка угля<select required value={specForm.coal_grade_id} onChange={e=>setSpecForm({...specForm,coal_grade_id:e.target.value})}><option value="">Выберите</option>{grades.filter(x=>x.is_active||x.id===Number(specForm.coal_grade_id)).map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Калорийность, ккал/кг<input inputMode="decimal" placeholder="5987,5" value={specForm.calorific_value} onChange={e=>setSpecForm({...specForm,calorific_value:e.target.value})}/></label><label>Влага, %<input inputMode="decimal" placeholder="13,5" value={specForm.moisture_pct} onChange={e=>setSpecForm({...specForm,moisture_pct:e.target.value})}/></label><label>Зола, %<input inputMode="decimal" placeholder="15,75" value={specForm.ash_pct} onChange={e=>setSpecForm({...specForm,ash_pct:e.target.value})}/></label><label>Действует с<input type="date" required value={specForm.valid_from} onChange={e=>setSpecForm({...specForm,valid_from:e.target.value})}/></label><fieldset><legend>Фракция</legend><input inputMode="decimal" aria-label="Минимум фракции" value={specForm.fraction_min_mm} onChange={e=>setSpecForm({...specForm,fraction_min_mm:e.target.value})}/><input inputMode="decimal" aria-label="Максимум фракции" value={specForm.fraction_max_mm} onChange={e=>setSpecForm({...specForm,fraction_max_mm:e.target.value})}/><select aria-label="Оператор" value={specForm.operator} onChange={e=>setSpecForm({...specForm,operator:e.target.value})}>{["<","<=","=",">=",">"].map(x=><option key={x}>{x}</option>)}</select><input inputMode="decimal" aria-label="Значение фракции" value={specForm.fraction_value} onChange={e=>setSpecForm({...specForm,fraction_value:e.target.value})}/></fieldset><button className="primary-action">{!selectedSpec?"Добавить":newVersion?"Создать новую версию":"Сохранить изменения"}</button>{selectedSpec&&<button type="button" onClick={resetSpec}>Отмена</button>}</form>}
  </div></main>;
}
