import { useEffect, useMemo, useRef, useState } from "react";
import type { AcceptanceForm, AcceptanceStatus, DirectoryItem, QueueItem } from "./types";

const EMPTY: AcceptanceForm = {shipment_date:"",act_number:"",transport_invoice_number:"",document_net_weight_t:"",supplier_id:"",coal_grade_id:"",uk_number:"",invoice_number:"",receiver_name:"",notes:""};
const REQUIRED: (keyof AcceptanceForm)[] = ["shipment_date","transport_invoice_number","document_net_weight_t","supplier_id","coal_grade_id","receiver_name"];
const STATUS: Record<AcceptanceStatus,string> = {WAITING:"Ожидает оформления",DRAFT:"Черновик",COMPLETED:"Оформлена"};
const PAGE_SIZE = 25;
const unsavedText = "Есть несохранённые изменения.\nПродолжить без сохранения?";
const massInput = (value:string) => { const normalized=value.replace(",", ".").replace(/[^0-9.]/g, ""); const [whole,...rest]=normalized.split("."); return rest.length ? `${whole}.${rest.join("")}` : whole; };
const displayWeight = (value:number|string|null) => value == null ? "Ожидается второе взвешивание / тара" : `${Number(value).toFixed(3)} т`;
const formFrom = (item:QueueItem):AcceptanceForm => item.acceptance ? Object.fromEntries(Object.keys(EMPTY).map(key=>[key,String((item.acceptance as unknown as Record<string,unknown>)[key]??"")])) as AcceptanceForm : {...EMPTY};

export function CoalAcceptancePage() {
  const [items,setItems]=useState<QueueItem[]>([]), [selected,setSelected]=useState<QueueItem|null>(null);
  const [dirs,setDirs]=useState<{suppliers:DirectoryItem[];coal_grades:DirectoryItem[]}>({suppliers:[],coal_grades:[]});
  const [form,setForm]=useState<AcceptanceForm>({...EMPTY}), [saved,setSaved]=useState(JSON.stringify(EMPTY));
  const [filters,setFilters]=useState({date_from:"",date_to:"",plate:"",invoice_number:"",supplier_id:"",coal_grade_id:"",status:""});
  const [page,setPage]=useState(1), [total,setTotal]=useState(0), [error,setError]=useState(""), [directoryError,setDirectoryError]=useState(""), [busy,setBusy]=useState(false), [conflict,setConflict]=useState(false);
  const firstField=useRef<HTMLInputElement>(null);
  const dirty=selected!==null && JSON.stringify(form)!==saved;
  const readonly=selected?.status==="COMPLETED";

  const loadQueue=async()=>{ try { const params=new URLSearchParams({page:String(page),page_size:String(PAGE_SIZE)}); Object.entries(filters).forEach(([k,v])=>v&&params.set(k,v)); const response=await fetch(`/api/coal-acceptance/queue?${params}`); if(!response.ok)throw new Error(); const data=await response.json(); setItems(data.items);setTotal(data.total);setError(""); } catch { setError("Не удалось загрузить очередь. Проверьте соединение с сервером."); } };
  const loadDirectories=async()=>{ try { const response=await fetch("/api/coal-acceptance/directories");if(!response.ok)throw new Error();setDirs(await response.json());setDirectoryError(""); } catch { setDirectoryError("Не удалось загрузить справочник поставщиков/марок"); } };
  useEffect(()=>{void loadQueue();},[page,filters]);
  useEffect(()=>{void loadDirectories();},[]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};const navigate=(event:Event)=>{if(dirty&&!confirm(unsavedText))event.preventDefault();};addEventListener("beforeunload",warn);addEventListener("app:navigate",navigate);return()=>{removeEventListener("beforeunload",warn);removeEventListener("app:navigate",navigate);};},[dirty]);

  const open=(item:QueueItem)=>{if(dirty&&!confirm(unsavedText))return;const next=formFrom(item);setSelected(item);setForm(next);setSaved(JSON.stringify(next));setConflict(false);setError("");setTimeout(()=>firstField.current?.focus());};
  const refreshCard=async()=>{if(!selected)return;try{const response=await fetch(`/api/coal-acceptance/${selected.trip_id}`);if(!response.ok)throw new Error();const item=await response.json();const next=formFrom(item);setSelected(item);setForm(next);setSaved(JSON.stringify(next));setConflict(false);setError("");}catch{setError("Не удалось обновить карточку.");}};
  const save=async(complete=false,goNext=false)=>{if(!selected||readonly)return;setBusy(true);setError("");setConflict(false);try{const body={...form,document_net_weight_t:form.document_net_weight_t||null,supplier_id:form.supplier_id?Number(form.supplier_id):null,coal_grade_id:form.coal_grade_id?Number(form.coal_grade_id):null,operator_name:localStorage.getItem("operator_name")};const url=`/api/coal-acceptance/${selected.trip_id}`;let response=await fetch(url,{method:selected.acceptance?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(selected.acceptance?{...body,expected_updated_at:selected.acceptance.updated_at}:body)});if(response.status===409){setConflict(true);return;}if(!response.ok)throw new Error(await response.text());let next=await response.json();if(complete){response=await fetch(`${url}/complete`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_updated_at:next.acceptance.updated_at,operator_name:localStorage.getItem("operator_name")})});if(response.status===409){setConflict(true);return;}if(!response.ok){if(response.status===422&&next.actual_net_weight_t==null)throw new Error("Оформление нельзя завершить: ещё отсутствует тара и фактическое нетто не определено.");throw new Error("Заполните все обязательные поля перед завершением оформления.");}next=await response.json();}const nextForm=formFrom(next);setSelected(next);setForm(nextForm);setSaved(JSON.stringify(nextForm));await loadQueue();if(goNext){const candidate=items.find(x=>x.trip_id!==selected.trip_id&&x.status!=="COMPLETED");if(candidate)open(candidate);}}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось сохранить карточку.");}finally{setBusy(false);}};

  const completed=REQUIRED.filter(key=>form[key].trim()!=="").length;
  const progress=Math.round(completed/REQUIRED.length*100);
  const stats=useMemo(()=>({waiting:items.filter(x=>x.status==="WAITING").length,draft:items.filter(x=>x.status==="DRAFT").length,done:items.filter(x=>x.status==="COMPLETED").length}),[items]);
  const updateFilter=(key:string,value:string)=>{setPage(1);setFilters(current=>({...current,[key]:value}));};
  const field=(key:keyof AcceptanceForm,title:string,type="text")=><label>{title}{REQUIRED.includes(key)&&<span className="required" aria-label="обязательное поле"> *</span>}<input ref={key==="shipment_date"?firstField:undefined} disabled={readonly} type={type} value={form[key]} onChange={event=>setForm({...form,[key]:key==="document_net_weight_t"?massInput(event.target.value):event.target.value})}/></label>;
  const nextEnabled=page*PAGE_SIZE<total;

  return <main className="acceptance-page">
    <div className="acceptance-heading"><div><h1>Приёмка угля</h1><p>Документальное оформление рейсов</p></div><a className="primary-action" href="/api/coal-acceptance/export.xlsx">Экспорт Excel</a></div>
    <section className="acceptance-toolbar" aria-label="Фильтры очереди">
      <label>Период с<input type="date" value={filters.date_from} onChange={e=>updateFilter("date_from",e.target.value)}/></label><label>по<input type="date" value={filters.date_to} onChange={e=>updateFilter("date_to",e.target.value)}/></label>
      <label>Госномер<input placeholder="Например, А123ВС" value={filters.plate} onChange={e=>updateFilter("plate",e.target.value)}/></label><label>№ ТН<input value={filters.invoice_number} onChange={e=>updateFilter("invoice_number",e.target.value)}/></label>
      <label>Поставщик<select value={filters.supplier_id} onChange={e=>updateFilter("supplier_id",e.target.value)}><option value="">Все</option>{dirs.suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Марка угля<select value={filters.coal_grade_id} onChange={e=>updateFilter("coal_grade_id",e.target.value)}><option value="">Все</option>{dirs.coal_grades.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
      <label>Статус<select value={filters.status} onChange={e=>updateFilter("status",e.target.value)}><option value="">Все</option>{Object.entries(STATUS).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><button type="button" onClick={()=>{setFilters({date_from:"",date_to:"",plate:"",invoice_number:"",supplier_id:"",coal_grade_id:"",status:""});setPage(1);}}>Очистить</button>
    </section>
    {directoryError&&<div className="acceptance-alert error">{directoryError} <button onClick={()=>void loadDirectories()}>Повторить</button></div>}
    {error&&<div className="acceptance-alert error">{error} <button onClick={()=>void loadQueue()}>Повторить</button></div>}
    <div className="acceptance-stats"><span>Ожидают <b>{stats.waiting}</b></span><span>Черновики <b>{stats.draft}</b></span><span>Оформлено <b>{stats.done}</b></span><span>Всего <b>{total}</b></span></div>
    <section className="acceptance-work"><div><div className="acceptance-table-wrap"><table className="acceptance-table"><thead><tr><th>Время</th><th>Госномер</th><th>Брутто</th><th>Тара</th><th>Нетто</th><th>№ ТН</th><th>Поставщик</th><th>Марка угля</th><th>Статус</th></tr></thead><tbody>{items.map(item=><tr key={item.trip_id} tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")open(item);}} onClick={()=>open(item)}><td>{new Date(item.entry_time).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}</td><td>{item.vehicle.license_plate||"—"}</td><td>{item.brutto_weight_kg==null?"—":`${(item.brutto_weight_kg/1000).toFixed(3)} т`}</td><td>{item.tare_weight_kg==null?"—":`${(item.tare_weight_kg/1000).toFixed(3)} т`}</td><td>{displayWeight(item.actual_net_weight_t)}</td><td>{item.acceptance?.transport_invoice_number||"—"}</td><td>{item.acceptance?.supplier?.name||"—"}</td><td>{item.acceptance?.coal_grade?.name||"—"}</td><td><span className={`acceptance-status ${item.status.toLowerCase()}`}>{STATUS[item.status]}</span></td></tr>)}</tbody></table>{!items.length&&!error&&<div className="acceptance-empty">По выбранным фильтрам рейсов нет.</div>}</div><div className="acceptance-pagination"><button disabled={page===1} onClick={()=>setPage(x=>x-1)}>Назад</button><span>Страница {page}</span><button disabled={!nextEnabled} onClick={()=>setPage(x=>x+1)}>Далее</button></div></div>
    {selected&&<form className="acceptance-card" onSubmit={e=>e.preventDefault()}><div className="card-title"><h2>Рейс №{selected.trip_id}</h2><span className={`acceptance-status ${selected.status.toLowerCase()}`}>{STATUS[selected.status]}</span></div>
      {conflict&&<div className="acceptance-alert error">Карточка была изменена другим оператором. Обновите данные перед повторным сохранением. <button type="button" onClick={()=>void refreshCard()}>Обновить карточку</button></div>}
      <section><h3>Данные системы</h3><div className="system-data"><span><b>Госномер:</b> {selected.vehicle.license_plate||"—"}</span><span><b>Въезд:</b> {new Date(selected.entry_time).toLocaleString("ru-RU")}</span><span><b>Выезд:</b> {selected.exit_time?new Date(selected.exit_time).toLocaleString("ru-RU"):"—"}</span><span><b>Брутто:</b> {selected.brutto_weight_kg==null?"—":`${(selected.brutto_weight_kg/1000).toFixed(3)} т`}</span><span><b>Тара:</b> {selected.tare_weight_kg==null?"Ожидается второе взвешивание":`${(selected.tare_weight_kg/1000).toFixed(3)} т`}</span><span><b>Фактическое нетто:</b> {displayWeight(selected.actual_net_weight_t)}</span><span><b>Lidar:</b> {selected.lidar?.status||"нет данных"}</span><span><b>Профилей:</b> {selected.lidar?.profiles_count??"—"}</span><span><b>Объём:</b> {selected.lidar?.volume_status||"—"}</span></div></section>
      <section><div className="progress-title"><h3>Данные накладной</h3><span>Заполнено {completed} из {REQUIRED.length} обязательных полей</span></div><div className="acceptance-progress" role="progressbar" aria-valuenow={completed} aria-valuemin={0} aria-valuemax={REQUIRED.length}><span style={{width:`${progress}%`}}/></div><div className="acceptance-fields">{field("shipment_date","Дата отгрузки","date")}{field("act_number","№ Акта")}{field("transport_invoice_number","№ транспортной накладной")}{field("document_net_weight_t","Масса по ТН, т")}<label>Грузоотправитель <span className="required">*</span><select disabled={readonly} value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:e.target.value})}><option value="">Выберите</option>{dirs.suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Марка угля <span className="required">*</span><select disabled={readonly} value={form.coal_grade_id} onChange={e=>setForm({...form,coal_grade_id:e.target.value})}><option value="">Выберите</option>{dirs.coal_grades.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{field("uk_number","№ УК")}{field("invoice_number","№ СФ")}{field("receiver_name","ФИО приёмосдатчика")}<label>Комментарий<textarea disabled={readonly} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div></section>
      <section><h3>Расчёт</h3><div className="calculated"><span>Фактическое нетто <b>{displayWeight(selected.actual_net_weight_t)}</b></span><span>Расхождение Ф-ТН <b>{selected.calculated.difference_t??"—"}</b></span><span>Допустимое расхождение <b>{selected.calculated.allowed_difference_t??"—"}</b></span><span>Недостача <b>{selected.calculated.shortage_t??"—"}</b></span><span>Излишек <b>{selected.calculated.excess_t??"—"}</b></span><span>Оприходовано <b>{selected.calculated.accepted_weight_t??"—"}</b></span><span>Договорная дата <b>определяется сервером</b></span></div></section>
      {!readonly&&<div className="acceptance-actions"><button type="button" disabled={busy} onClick={()=>void save(false)}>Сохранить черновик</button><button type="button" disabled={busy} onClick={()=>void save(false,true)}>Сохранить и следующий</button><button type="button" className="primary-action" disabled={busy||completed<REQUIRED.length||selected.actual_net_weight_t==null} onClick={()=>void save(true)}>Завершить оформление</button></div>}
    </form>}</section>
  </main>;
}
