import { useEffect, useMemo, useState } from "react";
import type { AcceptanceForm, DirectoryItem, QueueItem } from "./types";

const empty: AcceptanceForm = { shipment_date:"",act_number:"",transport_invoice_number:"",document_net_weight_t:"",supplier_id:"",coal_grade_id:"",uk_number:"",invoice_number:"",receiver_name:"",notes:"" };
const label: Record<string,string> = { WAITING:"Ожидает оформления",DRAFT:"Черновик",COMPLETED:"Оформлен" };
const inputMass = (value:string) => value.replace(",", ".").replace(/[^0-9.]/g, "");

export function CoalAcceptancePage() {
  const [items,setItems]=useState<QueueItem[]>([]), [selected,setSelected]=useState<QueueItem|null>(null);
  const [dirs,setDirs]=useState<{suppliers:DirectoryItem[];coal_grades:DirectoryItem[]}>({suppliers:[],coal_grades:[]});
  const [form,setForm]=useState<AcceptanceForm>(empty), [saved,setSaved]=useState(""), [search,setSearch]=useState("");
  const dirty=selected !== null && JSON.stringify(form)!==saved;
  const load=async()=>{ const [q,d]=await Promise.all([fetch(`/api/coal-acceptance/queue?plate=${encodeURIComponent(search)}`),fetch("/api/coal-acceptance/directories")]); if(!q.ok||!d.ok) throw new Error("backend offline"); setItems((await q.json()).items); setDirs(await d.json()); };
  useEffect(()=>{ void load(); },[search]);
  useEffect(()=>{ const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}}; addEventListener("beforeunload",warn); return()=>removeEventListener("beforeunload",warn); },[dirty]);
  const open=(x:QueueItem)=>{if(dirty&&!confirm("Есть несохранённые изменения. Закрыть карточку?"))return; const f=x.acceptance?Object.fromEntries(Object.keys(empty).map(k=>[k,String((x.acceptance as any)[k]??"")])) as AcceptanceForm:{...empty}; setSelected(x);setForm(f);setSaved(JSON.stringify(f));};
  const save=async(complete=false)=>{if(!selected)return; const body={...form,document_net_weight_t:form.document_net_weight_t||null,supplier_id:form.supplier_id?Number(form.supplier_id):null,coal_grade_id:form.coal_grade_id?Number(form.coal_grade_id):null,operator_name:localStorage.getItem("operator_name")}; const url=`/api/coal-acceptance/${selected.trip_id}`; let response=await fetch(url,{method:selected.acceptance?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(selected.acceptance?{...body,expected_updated_at:selected.acceptance.updated_at}:body)}); if(!response.ok)throw new Error(await response.text()); let next=await response.json(); if(complete){response=await fetch(`${url}/complete`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_updated_at:next.acceptance.updated_at,operator_name:localStorage.getItem("operator_name")})});if(!response.ok)throw new Error(await response.text());next=await response.json();} setSelected(next);setSaved(JSON.stringify(form));await load();};
  const stats=useMemo(()=>({waiting:items.filter(x=>x.status==="WAITING").length,draft:items.filter(x=>x.status==="DRAFT").length,done:items.filter(x=>x.status==="COMPLETED").length}),[items]);
  const field=(key:keyof AcceptanceForm,title:string,type="text")=><label>{title}<input autoFocus={key==="shipment_date"} type={type} value={form[key]} onChange={e=>setForm({...form,[key]:key==="document_net_weight_t"?inputMass(e.target.value):e.target.value})}/></label>;
  return <main className="acceptance-page"><div className="acceptance-heading"><div><h1>Приёмка угля</h1><p>Документальное оформление рейсов</p></div><a className="primary-action" href="/api/coal-acceptance/export.xlsx">Экспорт Excel</a></div>
    <section className="acceptance-toolbar"><input placeholder="Госномер / ТН / рейс" value={search} onChange={e=>setSearch(e.target.value)}/></section>
    <div className="acceptance-stats"><span>Ожидают <b>{stats.waiting}</b></span><span>Черновики <b>{stats.draft}</b></span><span>Оформлено <b>{stats.done}</b></span></div>
    <section className="acceptance-work"><div className="acceptance-table-wrap"><table className="acceptance-table"><thead><tr><th>Время</th><th>Госномер</th><th>Вес, т</th><th>№ ТН</th><th>Поставщик</th><th>Статус</th></tr></thead><tbody>{items.map(x=><tr key={x.trip_id} onClick={()=>open(x)}><td>{new Date(x.entry_time).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}</td><td>{x.vehicle.license_plate||"—"}</td><td>{x.actual_net_weight_t||"Ожидается тара"}</td><td>{x.acceptance?.transport_invoice_number||"—"}</td><td>{x.acceptance?.supplier?.name||"—"}</td><td><span className={`acceptance-status ${x.status.toLowerCase()}`}>{label[x.status]}</span></td></tr>)}</tbody></table></div>
    {selected&&<form className="acceptance-card" onSubmit={e=>e.preventDefault()}><h2>Рейс №{selected.trip_id}</h2><div className="system-data"><b>{selected.vehicle.license_plate}</b><span>{selected.vehicle.model||"Автомобиль"}</span><span>Фактический вес: {selected.actual_net_weight_t||"Ожидается тара"} т</span><span>Lidar: {selected.lidar?.status||"нет данных"}</span></div><h3>Данные накладной</h3><div className="acceptance-fields">{field("shipment_date","Дата отгрузки","date")}{field("act_number","№ Акта")}{field("transport_invoice_number","№ ТН")}{field("document_net_weight_t","Масса по ТН, т")}
      <label>Грузоотправитель<select value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:e.target.value})}><option value="">Выберите</option>{dirs.suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Марка угля<select value={form.coal_grade_id} onChange={e=>setForm({...form,coal_grade_id:e.target.value})}><option value="">Выберите</option>{dirs.coal_grades.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{field("uk_number","№ УК")}{field("invoice_number","№ СФ")}{field("receiver_name","ФИО приёмосдатчика")}<label>Комментарий<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>
      <div className="calculated"><span>Расхождение <b>{selected.calculated.difference_t??"—"}</b></span><span>Недостача <b>{selected.calculated.shortage_t??"—"}</b></span><span>Излишек <b>{selected.calculated.excess_t??"—"}</b></span><span>Оприходовано <b>{selected.calculated.accepted_weight_t??"—"}</b></span></div><div className="acceptance-actions"><button onClick={()=>void save(false)}>Сохранить черновик</button><button className="primary-action" onClick={()=>void save(true)}>Завершить оформление</button></div></form>}</section></main>;
}
