import {useEffect,useRef,useState,type CSSProperties,type KeyboardEvent,type PointerEvent} from "react";
import {fuelQualityApi} from "./api";
import type {FuelQualityForm,FuelQualityItem,FuelQualityStatus} from "./types";

const EMPTY:FuelQualityForm={sample_date:"",sample_name:"",calorimeter:"C200",sa_percent:"",alpha:"0.0015",wa_percent:"",aa_percent:"",wr_percent:"",hydrogen_input_percent:"",qb_a_1_kcal_kg:"",qb_a_2_kcal_kg:"",va_percent:"",lab_technician_name:"",wagon_numbers:"",invoice_number:"",fuel_consumption_note:""};
const NUMERIC=["sa_percent","alpha","wa_percent","aa_percent","wr_percent","hydrogen_input_percent","qb_a_1_kcal_kg","qb_a_2_kcal_kg","va_percent"];
const REQUIRED=["sample_date","sample_name","calorimeter",...NUMERIC,"lab_technician_name"];
const STATUS:Record<FuelQualityStatus,string>={DRAFT:"Черновик",COMPLETED:"Завершён",ARCHIVED:"Архив"};
const CALCULATED:Record<string,string>={qb_a_kcal_kg:"Qb_a",qs_a_kcal_kg:"Qs_a",ad_percent:"Ad",ar_percent:"Ar",vdaf_percent:"Vdaf",vr_percent:"Vr",sr_percent:"Sr",sd_percent:"Sd",qs_r_kcal_kg:"Qs_r",qi_a_kcal_kg:"Qi_a",hr_percent:"Hr",qi_r_kcal_kg:"Qi_r",qs_daf_kcal_kg:"Qs_daf",wmax_daf_percent:"Wmax_daf",qs_af_kcal_kg:"Qs_af",qb_daf_kcal_kg:"Qb_daf"};
const normalize=(value:string)=>{const clean=value.replace(",",".").replace(/[^0-9.]/g,"");const [a,...b]=clean.split(".");return b.length?`${a}.${b.join("")}`:a;};
const toForm=(item:FuelQualityItem)=>Object.fromEntries(Object.keys(EMPTY).map(key=>[key,String((item as unknown as Record<string,unknown>)[key]??"")]));
export const DEFAULT_SPLIT_RATIO=62;
const MIN_SPLIT_RATIO=25,MAX_SPLIT_RATIO=70,SPLIT_STEP=2,SPLIT_STORAGE_KEY="laboratory:fuel-quality:split-ratio";
const clampSplit=(value:number)=>Math.min(MAX_SPLIT_RATIO,Math.max(MIN_SPLIT_RATIO,value));
const storedSplit=()=>{const value=Number(localStorage.getItem(SPLIT_STORAGE_KEY));return Number.isFinite(value)&&value>=MIN_SPLIT_RATIO&&value<=MAX_SPLIT_RATIO?value:DEFAULT_SPLIT_RATIO;};

export function FuelQualityPage(){
 const [items,setItems]=useState<FuelQualityItem[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState<FuelQualityItem|null>(null),[form,setForm]=useState<FuelQualityForm>({...EMPTY}),[saved,setSaved]=useState(JSON.stringify(EMPTY)),[calculated,setCalculated]=useState<Record<string,string>>({}),[error,setError]=useState(""),[loading,setLoading]=useState(false),[page,setPage]=useState(0),[filters,setFilters]=useState({date_from:"",date_to:"",status:"",search:""}),[splitRatio,setSplitRatio]=useState(storedSplit),[resizing,setResizing]=useState(false);
 const first=useRef<HTMLInputElement>(null);const dirty=selected!==null&&JSON.stringify(form)!==saved;const readonly=selected?.status!=="DRAFT";const legacy=selected?.source==="LEGACY_EXCEL";const completeCount=REQUIRED.filter(key=>form[key]?.trim()).length;
 const load=async()=>{setLoading(true);try{const query=new URLSearchParams({limit:"25",offset:String(page*25)});Object.entries(filters).forEach(([key,value])=>value&&query.set(key,value));const data=await fuelQualityApi.list(query.toString());setItems(data.items);setTotal(data.total);setError("");}catch{setError("Не удалось загрузить журнал контроля топлива.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[filters,page]);
 useEffect(()=>{if(readonly||NUMERIC.some(key=>!form[key])){if(!readonly)setCalculated({});return;}const timer=setTimeout(()=>fuelQualityApi.calculate(Object.fromEntries(NUMERIC.map(key=>[key,form[key]]))).then(value=>{setCalculated(value);setError("");}).catch(e=>{setCalculated({});setError(e.message);}),250);return()=>clearTimeout(timer);},[form,readonly]);
 useEffect(()=>{const before=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};addEventListener("beforeunload",before);return()=>removeEventListener("beforeunload",before);},[dirty]);
 const confirmLeave=()=>!dirty||confirm("Есть несохранённые изменения.\nПродолжить без сохранения?");
 const open=(item:FuelQualityItem)=>{if(!confirmLeave())return;const next=toForm(item);setSelected(item);setForm(next);setSaved(JSON.stringify(next));setCalculated(item.calculated);};
 const createNew=()=>{if(!confirmLeave())return;setSelected({id:0,status:"DRAFT",source:"MANUAL",source_file:null,source_sheet:null,updated_at:"",sample_date:"",sample_name:"",calorimeter:"",wr_percent:"",wa_percent:"",aa_percent:"",sa_percent:"",va_percent:"",calculated:{}});setForm({...EMPTY});setSaved(JSON.stringify(EMPTY));setCalculated({});setTimeout(()=>first.current?.focus());};
 const save=async(complete=false)=>{if(!selected||readonly)return;setLoading(true);try{let next=selected.id?await fuelQualityApi.update(selected.id,form,selected.updated_at):await fuelQualityApi.create(form);if(complete)next=await fuelQualityApi.complete(next.id);const nextForm=toForm(next);setSelected(next);setForm(nextForm);setSaved(JSON.stringify(nextForm));setCalculated(next.calculated);setError("");await load();}catch(e){setError(e instanceof Error?e.message:"Ошибка сохранения");}finally{setLoading(false);}};
 const archive=async()=>{if(!selected||selected.status!=="COMPLETED")return;try{const next=await fuelQualityApi.archive(selected.id);setSelected(next);setCalculated(next.calculated);await load();}catch(e){setError(e instanceof Error?e.message:"Ошибка архивации");}};
 const input=(key:string,title:string,unit="")=><label><span>{title}{REQUIRED.includes(key)&&<b className="required"> *</b>}</span><div className="unit-input"><input ref={key==="sample_date"?first:undefined} disabled={readonly} type={key==="sample_date"?"date":"text"} value={form[key]} onChange={e=>setForm({...form,[key]:NUMERIC.includes(key)?normalize(e.target.value):e.target.value})}/>{unit&&<small>{unit}</small>}</div></label>;
 const applySplit=(value:number)=>{const next=clampSplit(Math.round(value));setSplitRatio(next);localStorage.setItem(SPLIT_STORAGE_KEY,String(next));};
 const resize=(event:PointerEvent<HTMLDivElement>)=>{if(!resizing||!Number.isFinite(event.clientX))return;const bounds=event.currentTarget.parentElement?.getBoundingClientRect();if(bounds?.width)applySplit((event.clientX-bounds.left)/bounds.width*100);};
 const startResize=(event:PointerEvent<HTMLDivElement>)=>{setResizing(true);event.currentTarget.setPointerCapture?.(event.pointerId);};
 const stopResize=(event:PointerEvent<HTMLDivElement>)=>{setResizing(false);event.currentTarget.releasePointerCapture?.(event.pointerId);};
 const resizeByKeyboard=(event:KeyboardEvent<HTMLDivElement>)=>{if(event.key!=="ArrowLeft"&&event.key!=="ArrowRight")return;event.preventDefault();applySplit(splitRatio+(event.key==="ArrowRight"?SPLIT_STEP:-SPLIT_STEP));};
 const updateFilter=(key:string,value:string)=>{setPage(0);setFilters(current=>({...current,[key]:value}));};const now=new Date();
 return <><div className="page-heading"><div><p className="eyebrow">Ежесуточный журнал</p><h1>Контроль топлива</h1><p>Лабораторные анализы и показатели A:M.</p></div><div className="heading-actions"><a className="button secondary" href={fuelQualityApi.exportUrl(now.getFullYear(),now.getMonth()+1)}>Экспорт Excel</a><button className="button primary" onClick={createNew}>Новый анализ</button></div></div>
 <section className="panel filters fuel-filters"><label><span>Поиск</span><input value={filters.search} onChange={e=>updateFilter("search",e.target.value)} placeholder="Проба, накладная, вагоны"/></label><label><span>Дата от</span><input type="date" value={filters.date_from} onChange={e=>updateFilter("date_from",e.target.value)}/></label><label><span>Дата до</span><input type="date" value={filters.date_to} onChange={e=>updateFilter("date_to",e.target.value)}/></label><label><span>Статус</span><select value={filters.status} onChange={e=>updateFilter("status",e.target.value)}><option value="">Все</option>{Object.entries(STATUS).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label></section>
 {error&&<div className="alert alert-error">{error} <button className="text-button" onClick={()=>void load()}>Повторить</button></div>}<div className={`fuel-work${resizing?" is-resizing":""}`} style={{gridTemplateColumns:`${splitRatio}fr 10px ${100-splitRatio}fr`} as CSSProperties}><section className="panel table-panel fuel-analyses" data-testid="fuel-analyses"><div className="panel-title"><div><h2>Анализы</h2><span>{total} записей</span></div></div><div className="table-scroll"><table><thead><tr><th>Дата</th><th>Проба</th><th>Wr</th><th>Ar</th><th>Ad</th><th>Vdaf</th><th>Sa</th><th>Qir</th><th>Статус</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className={selected?.id===item.id?"is-selected":undefined} tabIndex={0} aria-selected={selected?.id===item.id} onClick={()=>open(item)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();open(item);}}}><td>{new Date(`${item.sample_date}T00:00:00`).toLocaleDateString("ru-RU")}</td><td><strong>{item.sample_name}</strong>{item.source==="LEGACY_EXCEL"&&<span className="source-badge">Импорт Excel</span>}</td><td>{item.wr_percent}</td><td>{item.calculated.ar_percent}</td><td>{item.calculated.ad_percent}</td><td>{item.calculated.vdaf_percent}</td><td>{item.sa_percent}</td><td>{item.calculated.qi_r_kcal_kg}</td><td><span className={`status status-${item.status.toLowerCase()}`}>{STATUS[item.status]}</span></td></tr>)}</tbody></table>{!loading&&!items.length&&<div className="empty"><strong>Анализов не найдено</strong><p>Измените фильтры или создайте первый анализ.</p></div>}</div><div className="pagination"><span>Страница {page+1}</span><div><button disabled={!page} onClick={()=>setPage(x=>x-1)}>Назад</button><button disabled={(page+1)*25>=total} onClick={()=>setPage(x=>x+1)}>Далее</button></div></div></section><div className="fuel-split-handle" role="separator" aria-label="Изменить ширину панелей" aria-orientation="vertical" aria-valuemin={MIN_SPLIT_RATIO} aria-valuemax={MAX_SPLIT_RATIO} aria-valuenow={splitRatio} tabIndex={0} title="Перетащите для изменения ширины. Двойной щелчок — сброс" onPointerDown={startResize} onPointerMove={resize} onPointerUp={stopResize} onPointerCancel={stopResize} onDoubleClick={()=>applySplit(DEFAULT_SPLIT_RATIO)} onKeyDown={resizeByKeyboard}><span/></div>
 {selected&&<form className="fuel-card fuel-detail" data-testid="fuel-detail" onSubmit={e=>e.preventDefault()}><section className="panel form-section"><div className="panel-title"><div><h2>{selected.id?selected.sample_name:"Новый анализ"}</h2><span>{STATUS[selected.status]}</span></div></div>{legacy?<div className="legacy-note"><strong>Исходные данные отсутствуют — исторический импорт</strong><span>{selected.source_file} · лист {selected.source_sheet}</span></div>:<div className="form-grid">{input("sample_date","Дата пробы")}{input("sample_name","Наименование пробы")}{input("calorimeter","Калориметр")}{input("sa_percent","Sa","%")}{input("alpha","alpha")}{input("wa_percent","Wa","%")}{input("aa_percent","Aa","%")}{input("wr_percent","Wr","%")}{input("hydrogen_input_percent","H (поле PDF)","%")}{input("qb_a_1_kcal_kg","Qb(1)","ккал/кг")}{input("qb_a_2_kcal_kg","Qb(2)","ккал/кг")}{input("va_percent","Va","%")}{input("lab_technician_name","Лаборант")}{input("wagon_numbers","№ вагонов")}{input("invoice_number","№ накладной")}<label className="span-2"><span>Расход топлива / примечание</span><textarea disabled={readonly} value={form.fuel_consumption_note} onChange={e=>setForm({...form,fuel_consumption_note:e.target.value})}/></label></div>}</section><section className="panel form-section"><div className="panel-title"><div><h2>Расчётные показатели</h2><span>Источник истины — laboratory backend</span></div></div><div className="fuel-results">{Object.entries(CALCULATED).map(([key,title])=><span key={key}><small>{title}</small><b>{calculated[key]??"—"}</b><em>{key.includes("kcal")?"ккал/кг":"%"}</em></span>)}</div></section><section className="panel form-section"><div className="panel-title"><div><h2>Итог A:M</h2><span>Ежесуточный журнал</span></div></div><div className="fuel-summary">{[["Wr",form.wr_percent],["Wa",form.wa_percent],["Aa",form.aa_percent],["Ar",calculated.ar_percent],["Ad",calculated.ad_percent],["Va",form.va_percent],["Vdaf",calculated.vdaf_percent],["Vr",calculated.vr_percent],["Sa",form.sa_percent],["Sr",calculated.sr_percent],["Sd",calculated.sd_percent],["Qir",calculated.qi_r_kcal_kg]].map(([key,value])=><span key={key}><small>{key}</small><b>{value||"—"}</b></span>)}</div></section><div className="fuel-actions">{!readonly&&<><button className="button secondary" disabled={loading} type="button" onClick={()=>void save(false)}>Сохранить DRAFT</button><button className="button primary" disabled={loading||completeCount<REQUIRED.length||!calculated.qi_r_kcal_kg} type="button" onClick={()=>void save(true)}>Завершить</button></>}{selected.status==="COMPLETED"&&!legacy&&<button className="button secondary" type="button" onClick={()=>void archive()}>В архив</button>}</div></form>}</div></>;
}
